### ISSUE TITLE
[Web App] Add support/instructions for deployment in tomcat

### ISSUE THREAD

**Issue by luis100** [peshkira/c3po#33]

**Comment by peshkira** [comment]
which version?
it should be actually no problem. You just have to generate the war and put it in the tomcat deployment directory?
Have you tried this? What was the problem

**Comment by luis100** [comment]
Niels, from SB was the one that tested it and then Per told me that Play! framework has currently and incompatibility with Tomcat that will be solved on the next version. If it is so, we may as well just wait and use JBoss or Play! server in the meantime.

**Comment by ghost** [comment]
Hi, I run c3po using playframework, no problem. Regarding Tomcat version7 , I did generate a war from play writing command play war (no other arguments) . Then moved the war to tomcat webapps and started tomcat and access localhost:8080/c3po from a webbrowser. Nothing happend

**Comment by peshkira** [comment]
Hi Niels!

Did you first rename the war to ROOT.war? AFAIK the deployment of play wars works only on the root context, because of some problems with play. This should be fixed with the new version of Play 2.1 (which was released a couple of days ago), but I haven't had a chance to update to it.

I will have to take a look at the changelog and see what it entails for the code.
Anyway, please let me know if renaming the war does the trick for now.

**Comment by ghost** [comment]
Hi Petar

I have also a test where I renamed the war to ROOT and deployed it. Also I have updated the plugin to 0.8.1 
No luck for both test run

Is it ok to lunch c3po like localhost:8080/c3po ?

---

Fra: Petar Petrov [notifications@github.com]
Sendt: 7. februar 2013 13:24
Til: peshkira/c3po
Cc: Niels Bjarke Reimer
Emne: Re: [c3po] [Web App] Add support/instructions for deployment in tomcat (#33)

Hi Niels!

Did you first rename the war to ROOT.war? AFAIK the deployment of play wars works only on the root context, because of some problems with play. This should be fixed with the new version of Play 2.1 (which was released a couple of days ago), but I haven't had a chance to update to it.

I will have to take a look at the changelog and see what it entails for the code.
Anyway, please let me know if renaming the war does the trick for now.

**Comment by peshkira** [comment]
Hi!

Yes, if the ROOT.war is deployed successfully, then both localhost:8080/ and localhost:8080/c3po should work.
(provided of course that tomcat listens to port 8080).

Then there seems to be another problem. Are there any error logs during the tomcat deployment. Can you paste the relevant portions.

**Comment by ghost** [comment]
There are no errors in any of the files in tomcats log directory

**Comment by peshkira** [comment]
Today Per and me managed to deploy 0.2.0 in tomcat. He had some issue with mongo, but he was able to resolve it. The trick was to remove the ROOT (folder) from the the tomcat webapps folder and rename the war to ROOT.war.
You can ask him for the details. If you manage to do it, please consider closing this issue.

**Comment by ghost** [comment]
I’m happy to hear it works for you. I have again followed your instructions and can’t get it to work. Maybe I generate the war in a wrong way. Please send me or upload the war you are using.

**Comment by peshkira** [comment]
Start Mongo
Move the ROOT folder of your tomcat webapps folder to another location
drop this war in there: https://dl.dropbox.com/u/8290338/ROOT.war
start tomcat.

If it does not run, please send me the log files.

**Comment by ghost** [comment]
Hi Petar. 
The war file you have sent to me works fine.
Your war file is also twice as big as the one I have generated with Play. 
To generate the war I did write “play war” in the c3po-webapi directory, and play started to generate the war. But not correctly. The issue can be closed anyway

**Comment by peshkira** [comment]
Happy to hear that. This war is generated via: play package.

I will take a look and see what is going on with play war and if there is any difference. cheers!

**Comment by peshkira** [comment]
I am closing that issue, as it seems to work now and it is covered by the current guide. Once the next milestone is finished a better and more thorough guide will be added
