### ISSUE TITLE
failed to install with "mvn install"

### ISSUE THREAD

**Issue by gregor2005** [peshkira/c3po#35]
hi,

i tried to compile c3po with "mvn install" but there i get the following error:

WARNING: emptying DBPortPool to localhost:27017 b/c of error
java.io.IOException: couldn't connect to [<pc-name>/<internal ip>:27017] bc:java.net.ConnectException: Verbindungsaufbau abgelehnt

which service is needed to compile c3po?

greetings
grego

**Comment by peshkira** [comment]
Hi!

Some of the tests need a connection to a mongo database and from the error message, I assume that you haven't started mongo. Nonetheless, even if you do, the build will probably fail, as there is one failing test, which will be fixed in the next version. All that should be summarized here: https://github.com/peshkira/c3po/wiki/Setup-Guide

For now, I will suggest just skipping the tests: by using `mvn clean install -Dmaven.test.skip`.
Please let me know, if this resolves the problem. If yes, please close the issue. Otherwise, let me know what the problem is.

**Comment by gregor2005** [comment]
thanks worked perfect:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] C3PO .............................................. SUCCESS [1.762s]
[INFO] C3PO API .......................................... SUCCESS [3.928s]
[INFO] C3PO Core ......................................... SUCCESS [3.074s]
[INFO] C3PO Command Line App ............................. SUCCESS [1.159s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
