### ISSUE TITLE
Compile/build c3po

### ISSUE THREAD

**Issue by fojinamyk** [peshkira/c3po#68]
Hi,

I'm new on C3PO, i just cloned the projet and now i need to build the project (c3po-cmd). How to do ? 
I heard people talking that i need to compile C3PO with Play, but i don't know how.
JAVA 1.6 and MongoDB are installed.

thank you in advance for help and sorry for this noob question

**Comment by peshkira** [comment]
If you just need to use the command line, then please refer to this guide: https://github.com/peshkira/c3po/wiki/Usage-Guide
Basically, you can download a binary and just use it as described in the guide..

If you, really need to build the command line project, you do not need Play. (Play is only needed for the web application project)
Here is a Dev Guide, that will help you setup c3po's dev environment
https://github.com/peshkira/c3po/wiki/Development-Guide

Take a look at the 'How to Build' section
https://github.com/peshkira/c3po/wiki/Development-Guide#how-to-build

If this helps you, please close the issue, otherwise let me know, if I can be of assistance. Also please consider starring this repository

**Comment by fojinamyk** [comment]
Thanks, this really helped me.
