### ISSUE TITLE
Failed to load Main-Class manifest attribute from c3po-cmd-0.4.0.jar

### ISSUE THREAD

**Issue by shsdev** [peshkira/c3po#70]
It is not clear how to start the application. 

In the README it just says, type: 

java -jar c3po-cmd.jar

From the project directory? 

There is jar file created: /c3po-cmd/target/c3po-cmd-0.4.0.jar

But this one cannot be executed:

Failed to load Main-Class manifest attribute from c3po-cmd-0.4.0.jar

**Comment by peshkira** [comment]
Hi Sven!

Have you downloaded the correct jar from BinTray as stated in the User Guide.

If you take the normal jar from the target dir, you cannot run it, as it is a standard maven jar containing only the compiled sources. If you want to build the command line executable jar yourself with maven, please refer to the Developers Guide here: https://github.com/peshkira/c3po/wiki/Development-Guide#how-to-build and take a look at the `mvn assembly:assembly` command.

If this resolves your issue, please close it. Otherwise, please let me know, if I can assist you further.

**Comment by shsdev** [comment]
I see, it's actually good practice not to create a bundled jar in the install phase. Thank you!
